# Generated by Django 6.0.5 on 2026-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.CharField(max_length=1),
        ),
    ]
