# Generated by Django 6.0.5 on 2026-05-27 10:22

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_ticket_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.plane_image_path
            ),
        ),
    ]
